#!/bin/bash
green(){
	echo -e "\033[32m\033[01m$1\033[0m"
}
blue(){
	echo -e "\033[34m\033[01m$1\033[0m"
}
apt-get update
apt-get upgrade -y
apt-get install -y unzip
apt-get install -y nginx
systemctl enable nginx
systemctl stop nginx
sleep 3
bash -c "$(wget -O- https://raw.githubusercontent.com/trojan-gfw/trojan-quickstart/master/trojan-quickstart.sh)"
apt-get install -y socat
curl https://get.acme.sh | sh
blue "DOMAIN:"
read domain
mkdir /etc/nginx/ssl
~/.acme.sh/acme.sh --issue -d $domain --standalone
~/.acme.sh/acme.sh --install-cert -d $domain \
--key-file /etc/nginx/ssl/private.key \
--fullchain-file /etc/nginx/ssl/fullchain.cer \
--reloadcmd "service nginx force-reload"
cat > /etc/nginx/nginx.conf <<-EOF
events {
	worker_connections 1024;
}

http {
	sendfile on;
	keepalive_timeout 120;
	types_hash_max_size 2048;
	include /etc/nginx/mime.types;
	default_type application/octet-stream;
	access_log /var/log/nginx/access.log;
	error_log /var/log/nginx/error.log;
	client_max_body_size 20m;

	server {
		listen     80;
		server_name $domain;
		root /usr/share/nginx/html;
		index index.html;
	}
}
EOF
blue "PASSWORD:"
read password
cat > /usr/local/etc/trojan/config.json <<-EOF
{
    "run_type": "server",
    "local_addr": "0.0.0.0",
    "local_port": 443,
    "remote_addr": "127.0.0.1",
    "remote_port": 80,
    "password": [
        "$password"
    ],
    "log_level": 1,
    "ssl": {
        "cert": "/etc/nginx/ssl/fullchain.cer",
        "key": "/etc/nginx/ssl/private.key",
        "key_password": "",
        "cipher": "ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384",
        "cipher_tls13": "TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:TLS_AES_256_GCM_SHA384",
        "prefer_server_cipher": true,
        "alpn": [
            "http/1.1"
        ],
        "alpn_port_override": {
            "h2": 81
        },
        "reuse_session": true,
        "session_ticket": false,
        "session_timeout": 600,
        "plain_http_response": "",
        "curves": "",
        "dhparam": ""
    },
    "tcp": {
        "prefer_ipv4": false,
        "no_delay": true,
        "keep_alive": true,
        "reuse_port": false,
        "fast_open": false,
        "fast_open_qlen": 20
    },
    "mysql": {
        "enabled": false,
        "server_addr": "127.0.0.1",
        "server_port": 3306,
        "database": "trojan",
        "username": "trojan",
        "password": "",
        "cafile": ""
    }
}
EOF
cd /usr/share/nginx/html
rm -rf *
wget https://github.com/Holmetong/web/raw/master/web.zip
unzip web.zip
rm web.zip
systemctl start nginx
systemctl start trojan
systemctl enable trojan
green "DONE!"
